services:
  - type: web
    name: tts-platform
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python deploy.py --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
    autoDeploy: true
